version: '3'
services:
  server:
    container_name: hakatime
    image: 'mujx/hakatime:v1.7.3'
    environment:
      HAKA_DB_HOST: haka_db
      HAKA_DB_PORT: 5432
      HAKA_DB_NAME: test
      HAKA_DB_PASS: test
      HAKA_DB_USER: test
      HAKA_PORT: 3000
      HAKA_ENABLE_REGISTRATION: 'false'
      HAKA_SESSION_EXPIRY: '168'
      HAKA_LOG_LEVEL: info
      HAKA_ENV: dev
      HAKA_HTTP_LOG: 'true'
      # HAKA_REMOTE_WRITE_URL: wakapi url for remote write and use hakatime in vscode extension
      # HAKA_REMOTE_WRITE_TOKEN
    expose:
      - '3000'
  haka_db:
    container_name: haka_db
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    volumes:
      - 'hakatime_db_data:/var/lib/postgresql/data'
volumes:
  hakatime_db_data: {  }
